# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

env:
  - DJANGO_SETTINGS_MODULE=tests.settings

script: py.test -v --cov-report= --cov=formtools_addons tests

after_success:
  - codecov
